### ISSUE TITLE
Gem require

### ISSUE THREAD

**Issue by lukert33** [rock-doves-2014/EchoThatAPI#5]
@sgharms @stevecass Can you take a look at our gemfile and attendant configs? Ever since settings this up I've needed to require some gems in the file where I call them. Both byebug and dotenv do not seem to exist from the perspective of the app-at-large.

**Comment by stevecass** [comment]
Sure. I'll have a look.

**Comment by sgharms** [comment]
Luke: When you add stuff to the Gemfile, if you want to use it from the cli
you have to use `bundle exec`?  Or can you describe how you execute things
and that it doesn't work (i.e. within Rails?)

**Comment by lukert33** [comment]
Sure. For instance I just was trying to grab the params that come from the front end so I could use that exact format as a let variable for a new batch of rspec controller tests. I put a byebug in to stop the server can grab the params like so:

```
 def create
    hashtext = JSON.parse(params.first[0])
    text = hashtext["message"]
    url = hashtext["url"]
    byebug
    #$client.update("#{text} - #{url}")
    return 200
 end
```

The error I got from the server is: "NameError (undefined local variable or method `byebug' for #<EchosController:0x007fad9f269108>):
  app/controllers/echos_controller.rb:8:in`create'  "

This is after running bundle install just before booting up the rails server.

**Comment by lukert33** [comment]
changing the byebug line to `require "byebug"; byebug` gets the gem running, so I think that implies that bundle installed it.

**Comment by sgharms** [comment]
What if you run it with `bundle exec rspec` ?​

**Comment by lukert33** [comment]
This is actually a run of the server, so I can capture the exact format of the request sent from chrome. The controller#create method is triggered by a message from chrome. 

My specs are running fine (and not requiring byebug).

**Comment by stevecass** [comment]
Is this working properly now, Luke?

**Comment by lukert33** [comment]
No. I actually just ran into the issue again. Tried to call FactoryGirl in my rspec config and needed to require it in the file in order to have rails read it.

**Comment by stevecass** [comment]
I think the problem is the way you have set up dotenv, and your explicit initializers for bitly and co. When I removed those references, byebug worked normally. I think something is preventing rails auto-loading from working properly. I'll have a dig.

**Comment by lukert33** [comment]
Thank you!
